### ISSUE TITLE
IDE setup

### ISSUE THREAD

**Issue by Legion2** [AmyAssist/Amy-Web#21]
- [x] specify an IDE
- [x] describe the setup to develop the WebApp
- [x] code convetions
- [x] static analysis tool

**Comment by FlxB2** [comment]
Official Supported IDE is VS Code, others may be used but on your own risk

**Comment by FlxB2** [comment]
the setup process and how to develop for the app is specified [here](https://github.com/AmyAssist/Amy-Web/wiki/Set-up-Amy-Web-with-VS-Code) in the wiki

**Comment by Legion2** [comment]
service spec is not requierd for rest services

**Comment by Legion2** [comment]
use default VSCode formatter
