### ISSUE TITLE
The Backend URL should be configurable

### ISSUE THREAD

**Issue by Legion2** [AmyAssist/Amy-Web#26]
use https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage to store the backend URL in the users browser, so it must not entered every time.
Tasks:
- [x] The first time a User opens the WebApp he must enter the URL.
- [x] all Services Using the entered URL and not a hard coded one
- [x] the URL can be changed
- [x] the url is stored in the browser

**Comment by FlxB2** [comment]
#30
